service: interactions

provider:
  name: aws
  runtime: python3.6
  stage: prod
  profile: razor-admin

functions:
  get_users:
    handler: users.get_users
    events:
      - http:
          path: users
          method: get
  put_users:
    handler: users.put_users
    events:
      - http:
          path: users
          method: put
  post_users:
    handler: users.post_users
	events:
	  - http:
	      path: users
		  method: post
  post_user_point:
    handler: user.post_user_points
    events:
      -http:
        path: users/points
        method: post
  put_transaction:
    handler: transactions.put_transaction
	events:
	  - http:
	    path: transactions
		method: put
  get_prizes:
    handler: prizes.get_prizes
	events:
	  -http: prizes
	    path: transactions
		method: get